name: Hello Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello Roya!"

      - name: Show Date
        run: date

      - name: Finish
        run: echo "Workflow Finished!"

